version: '3.8'

services:
  postgres:
    image: postgres
    container_name: postgres-container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - postgrest-net
    ports:
      - "5432:5432"

  postgrest:
    image: postgrest/postgrest
    container_name: postgrest-container
    environment:
      PGRST_DB_URI: "postgres://postgres:postgres@postgres:5432/mydb"
      PGRST_DB_SCHEMA: "public"
      PGRST_DB_ANON_ROLE: "postgres"
    networks:
      - postgrest-net
    ports:
      - "3000:3000"

networks:
  postgrest-net:
