services:
  postgres:
    image: postgres
    container_name: postgres-container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pathfinder
      POSTGRES_SCHEMA: scanner
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - postgrest-net
    ports:
      - "5432:5432"

  postgrest:
    image: postgrest/postgrest
    container_name: postgrest-container
    environment:
      PGRST_DB_URI: "postgres://postgres:postgres@postgres:5432/pathfinder"
      PGRST_DB_SCHEMA: "scanner"
      PGRST_DB_ANON_ROLE: "postgres"
    networks:
      - postgrest-net
    ports:
      - "3000:3000"

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin-container
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com # Default login email
      PGADMIN_DEFAULT_PASSWORD: admin       # Default login password
    volumes:
      - C:/Users/frane/Source/Zavrsni/PGAdminData:/var/lib/pgadmin
      - ./servers.json:/pgadmin4/servers.json
    networks:
      - postgrest-net
    ports:
      - "5050:80"
    command: >
      sh -c "mkdir -p /var/lib/pgadmin &&
      cp /pgadmin4/servers.json /var/lib/pgadmin/servers.json &&
      /entrypoint.sh"

networks:
  postgrest-net:
